DROP DATABASE IF EXISTS collavrate;
CREATE DATABASE collavrate;

DROP TABLE IF EXISTS lines CASCADE;
CREATE TABLE lines (
	id				SERIAL PRIMARY KEY,
	token			VARCHAR(40) NOT NULL,
	line_segment 	INTEGER NOT NULL,
	x 				REAL NOT NULL,
	y 				REAL NOT NULL
);